Final Group Capstone Project
mavericks-db/BookRacers-Rails-Back-End pull request #34
Opened 2022-09-29 20:47 UTC by mavericks-db

## Final Group Capstone Project

*** [FrontEnd Pull Request Link](https://github.com/jssol/bookracers-frontend/pull/24) ***
[Deployed Link - FrontEnd](https://beautiful-alfajores-92bbef.netlify.app/)

*** [BackEnd Pull Request Link]() ***
[Deployed Link -BackEnd](https://pacific-garden-78390.herokuapp.com/)

### Project requirements

#### Basics
- You should follow the layout of [the provided design](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign). You should change only the titles, descriptions, and photos - in order to create a website about something other than motorcycles.
- Select a theme for your website - is it going to be a website for booking doctor appointments, booking online classes, or something else?

#### Features

**Core features - for teams of each size**
- The user logs in to the website, only by typing the username (a proper authenticated login is a requirement if your group is made of 5 people).
- In the navigation panel, the user can see links to:
    - Motorcycles/doctors/classes/items that you selected as a theme.
    - "Reserve" form.
    - "My reservations".
    - "Add motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).
    - "Delete motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).
- On the main page, the user can see a [list of motorcycles/doctors/classes/items that you selected as a theme](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005577).
    <p align="center">
      <img width="416" alt="list" src="https://user-images.githubusercontent.com/98527559/193132290-c6300954-c39b-4b9b-b1c5-5f7fd7025a07.png"></p>
- When the user selects a specific item, they can see the [details page](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005579) with its full description (skip the "Rotate image" button).
    - In the details page, the user can click the "Reserve" button (in the design you can see the "Configure" button - please replace it with the "Reserve" button).
    <p align="center">
      <img width="415" alt="details" src="https://user-images.githubusercontent.com/98527559/193132246-d5f59aa0-d6ec-4bae-8f20-a25e9217e606.png"></p>

- When the user clicks the "Add item" link in the navigation panel they can see a form for adding a new item.

- Make the app responsive, creating both mobile and desktop versions.

**If your team has 3-4 members these are the required features; otherwise, consider them as optional features.**
- When the user clicks the "Delete item" link in the navigation panel they can see a list of all items with title and "Delete" button.
    - When the user clicks the "Delete" button, the selected item is marked as removed and does not show on the main list anymore.
- To reserve an appointment, the user has to select a date and city (username and selected item are autofilled).
    - Use the design based on the ["Book a vespa test-ride"](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005583) and add all necessary inputs.
    - The user can also access the "Reserve" page from the navigation panel. In that case only username is autofilled.
    <p align="center">
     <img width="416" alt="booking" src="https://user-images.githubusercontent.com/98527559/193132212-9264954a-8490-4eca-9a64-3cd5d605db6a.png"></p>

- When the user clicks the "My reservations" link in the navigation panel they can see a list of their reservations (with information about item name, date and city).
- Add full documentation for your API.

**If your team has 5 members these are the required features; otherwise, consider them as optional features.**

- Implement proper user authentication from the front-end to the server.
- Make sure that the "Add item" and "Delete item" links are accessible only by users who are admins.

#### Technical set up
- Set up the repository/repositories on GitHub and use Gitflow.
- You should use Postgres as your database
- Use Rails to create backend API.
- Use React & Redux to create frontend UI.
- You can choose if you want to set up your project as two separate apps or as one.
- The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

2022-09-29 22:31 UTC, Meltrust requested changes
Hi @mavericks-db ,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Nice seeds✔️
-  App is working ✔️ 
-  Nice routing ✔️
-  Nice use of active storage ✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Suggested Changes ♻️
_Check the comments under the review._

You can use as many of my suggestions as you want.  If there is anything you would like to skip - feel free to do that.  However, I strongly recommend you take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2022-09-29 22:31 UTC, Meltrust commented on README.md
> +## [Go Live]()
- [ ] This link is broken.  Please, consider updating it.

2022-09-29 22:31 UTC, Meltrust commented on README.md
> +*** [Link to Live Demo]() ***
- [ ] This link to the live demo is broken, kindly consider updating it.

2022-09-29 22:31 UTC, Meltrust commented on README.md
> +Open a browser and go to: `https://localhost:3000` to view the app.
- [ ] Please, kindly add the `rails db:create`, `rails db:migrate`, and the `rails db:seed` that your users will need to run and seed the project database.

2022-09-29 22:31 UTC, Meltrust commented on spec/models/category_spec.rb
> +require 'rails_helper'
- [ ] When running the test suite, I got 15 failing ones:

![image](https://user-images.githubusercontent.com/57421823/193152983-15640a03-79e6-446c-8359-3eae84228bc7.png)

Kindly consider correcting these test, to ensure your app's integrity. 💪

2022-09-29 22:31 UTC, Meltrust commented on test/channels/application_cable/connection_test.rb
> +require 'test_helper'
- [ ] You are using Rspec, but the `test` folder is used by another test framework.  Please consider deleting the `test` folder if not being used.

2022-09-29 22:31 UTC, Meltrust commented on Gemfile
> +gem 'cancancan'
- [ ] Some gems in your `gemfile` are not being used.  It seems to be the case with `cancancan` for instance.  Please, kindly remove the gems that are obsolete for the project.

That way, the dependency overhead will be reduced 💪

2022-09-29 22:31 UTC, Meltrust commented on app/controllers/api/v1/reservations_controller.rb
> +    # @reservation.total_price =
- [ ] Please, kindly remove these old pieces of old commented code, to improve the cleanliness of the repo.  💪

2022-09-30 04:10 UTC, mavericks-db commented on README.md
> +## [Go Live]()
Done. Thanks.

2022-09-30 04:11 UTC, mavericks-db commented on README.md
> +*** [Link to Live Demo]() ***
Done. Thanks.

2022-09-30 04:11 UTC, mavericks-db commented on README.md
> +Open a browser and go to: `https://localhost:3000` to view the app.
Done. Thanks.

2022-09-30 04:11 UTC, mavericks-db commented on Gemfile
> +gem 'cancancan'
Done. Thanks.

2022-09-30 04:11 UTC, mavericks-db commented on app/controllers/api/v1/reservations_controller.rb
> +    # @reservation.total_price =
Removed. Thanks.

2022-09-30 04:13 UTC, mavericks-db commented on README.md
> +Open a browser and go to: `https://localhost:3000` to view the app.
Added. Thanks.

2022-09-30 07:04 UTC, mavericks-db commented on test/channels/application_cable/connection_test.rb
> +require 'test_helper'
Deleted. Thanks.

2022-09-30 14:40 UTC, mcrd25 approved these changes
Hi Team, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 
*A tip as you move unto to real world projects*
I'd recommend to make your tests better in the future, maybe you can get more specific with your tests - what do you mean for something to be valid? Is the message you are getting what you expect? What about when it's not valid, id the message you are getting what you expect? - it can be not valid and still not behave in the way you expect it to.


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-10-01 04:08 UTC, mwenyoa commented
Thanks @mavericks-db for having worked on the required changes and Thanks @mcrd25 for taking time for reviewing our project and giving us resource feedback that we can use as we build real life projects.
 Cheers and Happy coding.

2022-10-01 04:09 UTC, merged